spring:
  security:
    enabled: false
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/gadget_mart_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 8340
  context-path: /singer





